[package]
name = "php-ext-poker"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
aya_poker = "0.1.0"
ext-php-rs = "*"
rand = "0.10.0-rc.0"

[profile.release]
strip = "debuginfo"
